# Generated by Django 4.2.25 on 2025-11-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='updata_on',
            new_name='updated_on',
        ),
    ]
